import json
import os
from pathlib import Path
from src.utils.config import INSIGHTS_DATA_DIR, REPORTS_GENERATED_DIR, REPORTS_TEMPLATES_DIR
from .schemas import InsightBrief

class ReportWriterAgent:
    @staticmethod
    def write_json(brief: InsightBrief):
        # Write brief
        brief_path = INSIGHTS_DATA_DIR / "insight_brief.json"
        with open(brief_path, "w", encoding="utf-8") as f:
            json.dump(brief.model_dump(), f, indent=2)
            
        # Write cards separately for API convenience
        cards_path = INSIGHTS_DATA_DIR / "insight_cards.json"
        cards = [c.model_dump() for c in brief.insights]
        with open(cards_path, "w", encoding="utf-8") as f:
            json.dump(cards, f, indent=2)

    @staticmethod
    def write_markdown(brief: InsightBrief):
        md_content = f"# MarketPulse AI — Market Intelligence Brief\n\n"
        md_content += f"**Generated By:** {brief.generated_by}\n"
        md_content += f"**Summary:** {brief.summary}\n\n"
        
        md_content += "## Top Market Signals\n\n"
        for card in brief.insights:
            md_content += f"### {card.keyword} (Score: {card.trend_score:.1f})\n"
            md_content += f"- **Severity**: {card.severity}\n"
            md_content += f"- **Confidence**: {card.confidence_score:.1f}\n"
            md_content += f"- **Factual Explanation**: {card.factual_explanation}\n"
            md_content += f"- **Business Implication**: {card.business_implication}\n"
            md_content += f"- **Recommended Next Step**: {card.recommended_next_step}\n"
            md_content += f"- **Limitation**: {card.limitation}\n"
            md_content += f"- **Evidence**: {len(card.evidence_articles)} articles\n\n"

        report_path = REPORTS_GENERATED_DIR / "market_brief_latest.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(md_content)
