from fastapi import APIRouter, HTTPException
from typing import List, Dict, Any
from src.api.data_loader import data_loader
import pandas as pd

router = APIRouter()

@router.get("/seeds", response_model=List[Dict[str, Any]])
async def get_insight_seeds():
    """
    Returns the insight seeds generated by the analytics pipeline.
    Useful for populating initial explanation cards on the dashboard 
    or acting as ground truth for LLM prompts.
    """
    try:
        insight_seed_df = data_loader.get_data("insight_seed_metrics")
        if insight_seed_df is None or insight_seed_df.empty:
            raise FileNotFoundError("Missing insight_seed_metrics.csv data.")

        # Sort by severity (high > medium > low) if possible, else return as is
        df = insight_seed_df.copy()
        
        # Mapping severity to numeric for sorting
        severity_map = {"high": 3, "medium": 2, "low": 1}
        df['severity_num'] = df['severity'].map(severity_map).fillna(0)
        df = df.sort_values(by="severity_num", ascending=False).drop(columns=['severity_num'])

        data = df.to_dict(orient="records")
        return data

    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=f"Service Unavailable: {str(e)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
