from fastapi import APIRouter, HTTPException
from typing import List, Dict, Any
from src.api.data_loader import data_loader
import pandas as pd

router = APIRouter()

import json
from pathlib import Path
from src.utils.config import INSIGHTS_DATA_DIR

@router.get("/seeds", response_model=List[Dict[str, Any]])
async def get_insight_seeds():
    """
    Returns the insight seeds generated by the analytics pipeline or Module 7.
    """
    try:
        # First try to load the richer insights from Module 7
        insights_file = INSIGHTS_DATA_DIR / "insight_cards.json"
        if insights_file.exists():
            with open(insights_file, "r", encoding="utf-8") as f:
                data = json.load(f)
            return data

        # Fallback to the deterministic analytics seeds
        insight_seed_df = data_loader.get_data("insight_seed_metrics")
        if insight_seed_df is None or insight_seed_df.empty:
            raise FileNotFoundError("Missing insight_seed_metrics.csv data.")

        # Sort by severity (high > medium > low) if possible, else return as is
        df = insight_seed_df.copy()
        
        # Mapping severity to numeric for sorting
        severity_map = {"high": 3, "medium": 2, "low": 1}
        df['severity_num'] = df['severity'].map(severity_map).fillna(0)
        df = df.sort_values(by="severity_num", ascending=False).drop(columns=['severity_num'])

        data = df.to_dict(orient="records")
        return data

    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=f"Service Unavailable: {str(e)}")
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
