from pathlib import Path
from typing import List
from src.rag.schemas import RAGAnswer, RAGRunManifest
from src.utils.config import REPORTS_TEMPLATES_DIR, REPORTS_GENERATED_DIR

def write_rag_markdown_report(answers: List[RAGAnswer], manifest: RAGRunManifest):
    template_path = REPORTS_TEMPLATES_DIR / "rag_answer_template.md"
    report_path = REPORTS_GENERATED_DIR / "rag_answer_sample.md"
    
    if not template_path.exists():
        return
        
    with open(template_path, "r", encoding="utf-8") as f:
        content = f.read()
        
    content = content.replace("{{ questions_processed }}", str(manifest.questions_processed))
    content = content.replace("{{ answers_generated }}", str(manifest.answers_generated))
    content = content.replace("{{ ai_answers }}", str(manifest.ai_answers))
    content = content.replace("{{ rule_based_answers }}", str(manifest.rule_based_answers))
    content = content.replace("{{ generated_at }}", manifest.timestamp)
    content = content.replace("{{ total_citations_used }}", str(manifest.total_citations_used))
    
    ans_lines = []
    for ans in answers:
        ans_lines.append(f"### Q: {ans.question}")
        ans_lines.append(f"**Answer:** {ans.answer}")
        
        cit_str = ", ".join(ans.citation_ids) if ans.citation_ids else "None"
        ans_lines.append(f"- **Citations:** {cit_str}")
        ans_lines.append(f"- **Limitation:** {ans.limitation}")
        ans_lines.append(f"- *Generated by:* `{ans.generated_by}` | *Confidence:* {ans.confidence_note}\n")
        
        if ans.retrieved_evidence:
            ans_lines.append("**Retrieved Evidence:**")
            for ev in ans.retrieved_evidence:
                ans_lines.append(f"  - {ev.citation_id} {ev.title} ({ev.source})")
        ans_lines.append("\n---\n")
        
    content = content.replace("{{ answers_section }}", "\n".join(ans_lines) if ans_lines else "No questions answered.")
    
    REPORTS_GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    with open(report_path, "w", encoding="utf-8") as f:
        f.write(content)
